// <auto-generated />
using System;
using FitnessCenterApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenterApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522103716_UpdateMembershipTypes")]
    partial class UpdateMembershipTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("22180022")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the class");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the fitness class");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the fitness class in minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the fitness class");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the Instructor of the fitness class");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the fitness class");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the fitness class");

                    b.Property<DateTime>("ScheduleDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Scheduled date and time of the fitness class");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("FitnessClasses", "22180022", t =>
                        {
                            t.HasTrigger("TR_FitnessClasses_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Description = "Спокойна и хармонична йога сесия, идеална за рестарт на деня и подобряване на фокуса.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 1,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6374),
                            Name = "Сутрешна Йога",
                            Price = 15.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Description = "Интензивна интервална тренировка, създадена да изгори максимален брой калории за кратко време.",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 2,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6385),
                            Name = "HIIT Предизвикателство",
                            Price = 20.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 16, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Description = "Забавен и енергичен зумба клас, подходящ за всички нива. Танцувайте и отслабвайте!",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1522898467493-49726bf28798?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 3,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6392),
                            Name = "Зумба Танци",
                            Price = 15.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 17, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            Description = "Тренировка за заздравяване на коремните мускули, подобряване на стойката и гъвкавостта.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 4,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6398),
                            Name = "Пилатес за Ядрото",
                            Price = 18.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 18, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            Description = "Въвеждащ клас в силовите тренировки с акцент върху правилната техника и безопасност.",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 5,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6404),
                            Name = "Основи на Силовите Тренировки",
                            Price = 25.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 19, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 12,
                            Description = "Научете основните техники на смесените бойни изкуства в сигурна и мотивираща среда.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1555597673-b21d5c935865?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 6,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6409),
                            Name = "ММА Основи",
                            Price = 30.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 15,
                            Description = "Тежка комплексна тренировка с тежести, гимнастика и кардио. Само за напреднали!",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 7,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6414),
                            Name = "Кросфит за Напреднали",
                            Price = 25.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 21, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 12,
                            Description = "Освежаваща водна тренировка в басейна. Идеална за раздвижване без натоварване на ставите.",
                            Duration = 50,
                            ImageUrl = "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 8,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6419),
                            Name = "Аква Аеробика",
                            Price = 20.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 16,
                            Description = "Клас, насочен към базови боксови комбинации, движение с крака и кардио издръжливост.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 9,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6424),
                            Name = "Бокс за Начинаещи",
                            Price = 25.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 20,
                            Description = "Интензивно колоездене на закрито с мотивираща музика. Изгорете до 600 калории!",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1534438097545-a2c22c57f2df?auto=format&fit=crop&w=800&q=80",
                            InstructorId = 10,
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6429),
                            Name = "Спининг Маратон",
                            Price = 18.00m,
                            ScheduleDateTime = new DateTime(2026, 7, 24, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClassRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FitnessClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "FitnessClassId");

                    b.HasIndex("FitnessClassId");

                    b.ToTable("FitnessClassRegistrations", "22180022", t =>
                        {
                            t.HasTrigger("TR_FitnessClassRegistrations_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the event");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the fitness event");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("End date of the fitness event");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the fitness event");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Location of the fitness event");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start date of the fitness event");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title of the fitness event");

                    b.HasKey("Id");

                    b.ToTable("FitnessEvents", "22180022", t =>
                        {
                            t.HasTrigger("TR_FitnessEvents_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            Description = "Присъединете се към вълнуващ 10 км маратон през централните улици на града.",
                            EndDate = new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1530143311094-34d807799e8f?auto=format&fit=crop&w=800&q=80",
                            Location = "Площад Център",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6613),
                            StartDate = new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Пролетен Градски Маратон"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            Description = "Предизвикателен поход до върха с група от ентусиасти и професионални водачи.",
                            EndDate = new DateTime(2026, 8, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=800&q=80",
                            Location = "Хижа Алеко",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6621),
                            StartDate = new DateTime(2026, 8, 20, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Планински Поход Витоша"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            Description = "Живописна разходка около езерото. Перфектна възможност за лека кардио активност на чист въздух.",
                            EndDate = new DateTime(2026, 10, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1506535995048-63737b794f83?auto=format&fit=crop&w=800&q=80",
                            Location = "Панчарево",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6630),
                            StartDate = new DateTime(2026, 10, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Есенна Разходка край Езерото"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 200,
                            Description = "Празнично 5 км бягане през снежния парк, средствата от което отиват за благотворителност.",
                            EndDate = new DateTime(2026, 12, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1512361436605-a484fc5e943c?auto=format&fit=crop&w=800&q=80",
                            Location = "Южен Парк",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6637),
                            StartDate = new DateTime(2026, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Зимно Благотворително Бягане"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 40,
                            Description = "Отпуснете се с ранна йога сесия под звуците на морските вълни.",
                            EndDate = new DateTime(2026, 7, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
                            Location = "Слънчев Бряг",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6644),
                            StartDate = new DateTime(2026, 7, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Лятна Йога на Плажа"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 20,
                            Description = "Основи на водолазното гмуркане. Научете се да дишате под вода с професионални инструктори.",
                            EndDate = new DateTime(2026, 9, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
                            Location = "Спортен Басейн",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6652),
                            StartDate = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Курс по Гмуркане"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 50,
                            Description = "Вътрешен клубен турнир по вдигане на тежести. Елате да премерите сили с най-добрите!",
                            EndDate = new DateTime(2026, 10, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80",
                            Location = "Главна Фитнес Зала",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6660),
                            StartDate = new DateTime(2026, 10, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Турнир по Вдигане на Тежести"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 30,
                            Description = "Двудневно бягство от града, изпълнено с медитация, йога и здравословна храна.",
                            EndDate = new DateTime(2026, 9, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80",
                            Location = "Еко Комплекс 'Балкан'",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6666),
                            StartDate = new DateTime(2026, 9, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Уикенд Йога Ретрийт"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 60,
                            Description = "Интензивен фитнес лагер на открито. Комбинация от военна подготовка и кардио.",
                            EndDate = new DateTime(2026, 8, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80",
                            Location = "Борисова Градина",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6675),
                            StartDate = new DateTime(2026, 8, 5, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Фитнес Буткемп на Открито"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 100,
                            Description = "Семинар за изготвяне на хранителен режим, воден от топ диетолози.",
                            EndDate = new DateTime(2026, 11, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80",
                            Location = "Конферентна Зала",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6684),
                            StartDate = new DateTime(2026, 11, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Мастърклас по Здравословно Хранене"
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEventRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("FitnessEventRegistrations", "22180022", t =>
                        {
                            t.HasTrigger("TR_FitnessEventRegistrations_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Instructor's biography");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's first name");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the instructor");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's last name");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's primary specialization");

                    b.HasKey("Id");

                    b.ToTable("Instructors", "22180022", t =>
                        {
                            t.HasTrigger("TR_Instructors_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Натали е сертифициран йога инструктор с над 10 години опит. Тя е посветена на това да помага на хората да постигнат хармония между тяло и дух.",
                            FirstName = "Натали",
                            ImageUrl = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
                            LastName = "Асатрян",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6724),
                            Specialization = "Йога"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Уорън е фитнес треньор, специализиран във високоинтензивни интервални тренировки (HIIT). Обича да мотивира клиентите си да надскачат собствените си граници.",
                            FirstName = "Уорън",
                            ImageUrl = "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=800&q=80",
                            LastName = "Скот",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6726),
                            Specialization = "HIIT"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Емили е инструктор по Зумба с богат опит в танците. Тя създава забавна и енергична атмосфера, в която тренировката се усеща като парти.",
                            FirstName = "Емили",
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
                            LastName = "Джонсън",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6728),
                            Specialization = "Зумба"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Оливия е сертифициран Пилатес инструктор. Нейната страст е да помага на хората да подобрят стойката си, гъвкавостта и силата на ядрото.",
                            FirstName = "Оливия",
                            ImageUrl = "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=800&q=80",
                            LastName = "Уилямс",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6730),
                            Specialization = "Пилатес"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Улф е треньор по силови тренировки и вдигане на тежести. Специализира в изграждането на мускулна маса и правилна техника на изпълнение.",
                            FirstName = "Улф",
                            ImageUrl = "https://images.unsplash.com/photo-1567598508481-65985588e295?auto=format&fit=crop&w=800&q=80",
                            LastName = "Джеймисън",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6731),
                            Specialization = "Силови тренировки"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Конър е професионален ММА боец и мотиватор. В неговите класове ще научите основите на бойните изкуства и ще изградите желязна дисциплина.",
                            FirstName = "Конър",
                            ImageUrl = "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80",
                            LastName = "Макгрегър",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6733),
                            Specialization = "ММА"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Митко е бивш състезател по Кросфит. Тренировките му са интензивни, комплексни и гарантират бързи резултати за издръжливост и сила.",
                            FirstName = "Димитър",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
                            LastName = "Петров",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6771),
                            Specialization = "Кросфит"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Мария е инструктор по водна аеробика. Нейните тренировки са щадящи за ставите, но изключително ефективни за изгаряне на калории.",
                            FirstName = "Мария",
                            ImageUrl = "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80",
                            LastName = "Иванова",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6773),
                            Specialization = "Аква Аеробика"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Георги е треньор по бокс с дългогодишен опит. Подходящ както за начинаещи, така и за напреднали, желаещи да подобрят техниката си.",
                            FirstName = "Георги",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80",
                            LastName = "Георгиев",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6775),
                            Specialization = "Бокс"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Елена води едни от най-енергичните спининг класове в центъра. Музиката ѝ е мотивираща, а натоварването - гарантирано.",
                            FirstName = "Елена",
                            ImageUrl = "https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=800&q=80",
                            LastName = "Стоянова",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6776),
                            Specialization = "Спининг"
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Log_22180022", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the operation was performed");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Type of operation performed (e.g., INSERT, UPDATE, DELETE)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the table where the operation occurred");

                    b.HasKey("Id");

                    b.ToTable("log_22180022", "22180022", t =>
                        {
                            t.HasComment("Log table for tracking database changes");
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId", "MembershipTypeId");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("MembershipRegistrations", "22180022", t =>
                        {
                            t.HasTrigger("TR_MembershipRegistrations_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedSpaProceduresPerWeek")
                        .HasColumnType("int")
                        .HasComment("Number of allowed spa procedures per week. 0 means no access.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the plan benefits");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration in days");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the membership plan");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the membership plan");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the membership");

                    b.HasKey("Id");

                    b.ToTable("MembershipTypes", "22180022", t =>
                        {
                            t.HasTrigger("TR_MembershipTypes_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedSpaProceduresPerWeek = 0,
                            Description = "Стандартен месечен абонамент. Включва неограничен достъп до фитнес залата и всички групови класове. Този план не включва право на записване за СПА процедури.",
                            Duration = 30,
                            ImageUrl = "/img/membership/Basic.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6812),
                            Name = "Основен план",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 2,
                            AllowedSpaProceduresPerWeek = 1,
                            Description = "Двумесечен абонамент за активни трениращи. Включва пълен достъп до фитнес залата, всички класове и право на 1 резервация за СПА процедура на седмица.",
                            Duration = 60,
                            ImageUrl = "/img/membership/Elite.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6814),
                            Name = "Елитен план",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 3,
                            AllowedSpaProceduresPerWeek = 5,
                            Description = "Шестмесечен абонамент с висока добавена стойност. Гарантира достъп до всички съоръжения и ви дава право на до 5 резервации за СПА процедури на седмица.",
                            Duration = 180,
                            ImageUrl = "/img/membership/Premium.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6816),
                            Name = "Премиум план",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 4,
                            AllowedSpaProceduresPerWeek = 99,
                            Description = "Ексклузивен годишен абонамент за най-отдадените. Включва пълен достъп до фитнес залата, всички класове и най-високия възможен седмичен лимит за резервация на СПА процедури.",
                            Duration = 365,
                            ImageUrl = "/img/membership/Vip.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6818),
                            Name = "ВИП годишен план",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 5,
                            AllowedSpaProceduresPerWeek = 0,
                            Description = "Специално предложение за студенти на УНСС. Осигурява пълен достъп до фитнес залата и всички тренировъчни класове. Планът не включва право на резервации за СПА процедури.",
                            Duration = 30,
                            ImageUrl = "/img/membership/UNWE.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6819),
                            Name = "Студентски план",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 6,
                            AllowedSpaProceduresPerWeek = 0,
                            Description = "Месечен абонамент с достъп до фитнес залата всеки ден, валиден за посещения в часовия интервал от 08:00 до 16:00 ч. Планът не включва право на резервации за СПА процедури.",
                            Duration = 30,
                            ImageUrl = "/img/membership/Daytime.png",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6821),
                            Name = "Дневен план",
                            Price = 45.99m
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the procedure");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the spa procedure");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the spa procedure in minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the spa procedure");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Spa type");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the spa procedure");

                    b.HasKey("Id");

                    b.ToTable("SpaProcedures", "22180022", t =>
                        {
                            t.HasTrigger("TR_SpaProcedures_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5,
                            Description = "Успокояващ масаж с бавни и плавни движения за облекчаване на напрежението и стреса.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6856),
                            Name = "Релаксиращ Масаж",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Description = "Подмладяваща процедура за лице, която подхранва, хидратира и освежава кожата.",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6858),
                            Name = "Терапия за Лице",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Description = "Сесия с етерични масла, която стимулира сетивата и насърчава пълното отпускане.",
                            Duration = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6860),
                            Name = "Ароматерапия",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3,
                            Description = "Терапевтичен масаж, използващ гладки, нагряти камъни за дълбоко отпускане на мускулите.",
                            Duration = 75,
                            ImageUrl = "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6862),
                            Name = "Масаж с Горещи Камъни",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Description = "Масаж, насочен към по-дълбоките слоеве на мускулната тъкан за освобождаване на хронично напрежение.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1519824145371-29681b328e11?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6864),
                            Name = "Дълбокотъканен Масаж",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            Description = "Детоксикираща процедура за тяло с богати на хранителни вещества водорасли за стягане на кожата.",
                            Duration = 90,
                            ImageUrl = "https://images.unsplash.com/photo-1544161514-93c68383a542?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6866),
                            Name = "Обвиване с Водорасли",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            Description = "Дълбоко проникваща топлина, която подпомага детоксикацията, отслабването и релаксацията.",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1583416750470-965b2707b355?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6868),
                            Name = "Инфрачервена Сауна",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 8,
                            Description = "Пречистваща парна баня, обогатена с лечебни билки за отваряне на порите и дихателните пътища.",
                            Duration = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6869),
                            Name = "Парна Баня с Билкови Екстракти",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 1,
                            Description = "Студова терапия, изключително ефективна за бързо възстановяване на мускулите след тежка тренировка.",
                            Duration = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1583416750470-965b2707b355?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6871),
                            Name = "Криотерапия за Възстановяване",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            Description = "Специализиран енергичен масаж, който използва бамбукови пръчки за дълбок дренаж на тъканите.",
                            Duration = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=800&q=80",
                            ModifiedOn_22180022 = new DateTime(2026, 5, 22, 10, 37, 14, 364, DateTimeKind.Utc).AddTicks(6873),
                            Name = "Спортен Масаж с Бамбукови Пръчки",
                            Price = 60.00m
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the registration");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("The specific date and time the user booked this procedure");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<int>("SpaProcedureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SpaProcedureId");

                    b.ToTable("SpaRegistrations", "22180022", t =>
                        {
                            t.HasTrigger("TR_SpaRegistrations_Log");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "22180022");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.Instructor", "Instructor")
                        .WithMany("FitnessClasses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClassRegistration", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.FitnessClass", "FitnessClass")
                        .WithMany("FitnessClassRegistrations")
                        .HasForeignKey("FitnessClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessClass");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEventRegistration", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.FitnessEvent", "FitnessEvent")
                        .WithMany("FitnessEventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessEvent");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipRegistration", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Data.Models.MembershipType", "MembershipType")
                        .WithMany("MembershipRegistrations")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaRegistration", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Data.Models.SpaProcedure", "SpaProcedure")
                        .WithMany("SpaRegistrations")
                        .HasForeignKey("SpaProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("SpaProcedure");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.Navigation("FitnessClassRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEvent", b =>
                {
                    b.Navigation("FitnessEventRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Instructor", b =>
                {
                    b.Navigation("FitnessClasses");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipType", b =>
                {
                    b.Navigation("MembershipRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaProcedure", b =>
                {
                    b.Navigation("SpaRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
