// <auto-generated />
using System;
using FitnessCenterApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenterApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409133525_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("22180022")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the class");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the fitness class");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the fitness class in minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the fitness class");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the Instructor of the fitness class");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the fitness class");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the fitness class");

                    b.Property<DateTime>("ScheduleDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Scheduled date and time of the fitness class");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("FitnessClasses", "22180022");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Description = "A calm and peaceful yoga session to start your day.",
                            Duration = 60,
                            ImageUrl = "https://yogajala.com/wp-content/uploads/8-Benefits-Of-Morning-Yoga.jpg",
                            InstructorId = 1,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6474),
                            Name = "Morning Yoga",
                            Price = 50.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 5, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Description = "An intense, high-energy interval training session.",
                            Duration = 45,
                            ImageUrl = "https://i.ytimg.com/vi/66_hHeSUrzU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQjZQw/2.jpg",
                            InstructorId = 2,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6484),
                            Name = "HIIT Challenge",
                            Price = 50.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Description = "A fun and energetic Zumba dance class for all levels.",
                            Duration = 60,
                            ImageUrl = "https://i.ytimg.com/vi/N3wBXogMYfM/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGGUgUihUMA8=&rs=AOn4CLD9yvCPKa7mHvL_lLUQr-TvnlNYRw",
                            InstructorId = 3,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6492),
                            Name = "Zumba Dance",
                            Price = 90.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            Description = "Strengthen your core and improve posture with this Pilates class.",
                            Duration = 60,
                            ImageUrl = "https://media.self.com/photos/5b9c24c208e0b96633983ce8/2:1/w_2580,c_limit/pilates-butt-core-workout.jpg",
                            InstructorId = 4,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6498),
                            Name = "Pilates Core",
                            Price = 85.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 7, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            Description = "An introductory strength training session focusing on weightlifting techniques.",
                            Duration = 45,
                            ImageUrl = "https://www.jefit.com/_next/image?url=https%3A%2F%2Fcdn.jefit.com%2Fuc%2Ffile%2Fc34238b8cd6e3cf7%2F1.jpg&w=3840&q=75",
                            InstructorId = 5,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6504),
                            Name = "Strength Training Basics",
                            Price = 95.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 12,
                            Description = "Learn the basics of ММА in this high-energy and engaging class.",
                            Duration = 30,
                            ImageUrl = "https://mf.b37mrtl.ru/rbthmedia/images/2018.02/article/5a93bf3385600a57b0096f7e.jpg",
                            InstructorId = 6,
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6510),
                            Name = "ММА Essentials",
                            Price = 150.00m,
                            ScheduleDateTime = new DateTime(2024, 12, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClassRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FitnessClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "FitnessClassId");

                    b.HasIndex("FitnessClassId");

                    b.ToTable("FitnessClassRegistrations", "22180022");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the event");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the fitness event");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("End date of the fitness event");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the fitness event");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Location of the fitness event");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start date of the fitness event");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title of the fitness event");

                    b.HasKey("Id");

                    b.ToTable("FitnessEvents", "22180022");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            Description = "Join us for a thrilling 10K spring marathon through the city streets.",
                            EndDate = new DateTime(2025, 4, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.chicagospringhalf.com/wp-content/uploads/sites/32/2023/05/2022_SPRCHI_RaceDay_Ali_282-1024x683.jpg",
                            Location = "Downtown City Center",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6697),
                            StartDate = new DateTime(2025, 4, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spring City Marathon"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            Description = "A challenging hike to the top of the mountain with stunning views.",
                            EndDate = new DateTime(2025, 7, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.reserveamerica.com/articles/wp-content/uploads/2024/07/11174967-1e85-45df-8097-ac30b3bb1c34.jpg",
                            Location = "Rocky Mountain Trail",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6706),
                            StartDate = new DateTime(2025, 7, 15, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mountain Peak Hike"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            Description = "A scenic walk around the beautiful autumn lake. Perfect for relaxation and exercise.",
                            EndDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.stockcake.com/public/c/a/0/ca09354d-17f0-4693-b9d3-fb2d399a07c1_large/autumn-lakeside-walk-stockcake.jpg",
                            Location = "Autumn Lake Park",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6713),
                            StartDate = new DateTime(2025, 10, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Autumn Lake Walk"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 200,
                            Description = "A festive 5K run through a snowy winter park.",
                            EndDate = new DateTime(2025, 12, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0203/9788/3467/files/Craft_AW22_ADV_SubZ_Wool-LS-Tee_4_1024x1024.jpg?v=1695349527",
                            Location = "Snowy Pines Park",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6720),
                            StartDate = new DateTime(2025, 12, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Winter Wonderland Run"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 40,
                            Description = "Relax and stretch with a peaceful yoga session on the beach.",
                            EndDate = new DateTime(2025, 6, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.townofbethanybeach.com/ImageRepository/Document?documentID=7156",
                            Location = "Golden Sands Beach",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6727),
                            StartDate = new DateTime(2025, 6, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summer Beach Yoga"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 20,
                            Description = "Diving is the sport of jumping or falling into water from a platform or springboard, often with acrobatics. It is part of the Olympic Games and also enjoyed recreationally as a non-competitive activity.",
                            EndDate = new DateTime(2025, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://daysym.com/wp-content/uploads/2024/01/dream-about-scuba-diving.jpg",
                            Location = "Blue hole",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6736),
                            StartDate = new DateTime(2025, 9, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Diving"
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEventRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("FitnessEventRegistrations", "22180022");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Instructor's biography");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's first name");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the instructor");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's last name");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Instructor's primary specialization");

                    b.HasKey("Id");

                    b.ToTable("Instructors", "22180022");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Natalie is a certified yoga instructor with over 10 years of experience. She is passionate about helping others achieve their fitness goals and improve their overall well-being.",
                            FirstName = "Natalie",
                            ImageUrl = "https://horizonweekly.ca/wp-content/uploads/2021/01/Nat-2.jpg",
                            LastName = "Asatryan",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6776),
                            Specialization = "Yoga"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Warren is a certified personal trainer and fitness coach. He specializes in high-intensity interval training (HIIT) and enjoys helping clients push their limits and reach their full potential.",
                            FirstName = "Warren",
                            ImageUrl = "https://images.squarespace-cdn.com/content/v1/651489d366d19e59b7bbf9cf/a68428a6-992f-45a4-adfc-1b5a75e5cfda/Warren_square500.jpg",
                            LastName = "Scott",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6778),
                            Specialization = "HIIT"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Emily is a certified Zumba instructor with a background in dance and fitness. She loves creating a fun and inclusive environment where everyone can enjoy the benefits of Zumba.",
                            FirstName = "Emily",
                            ImageUrl = "https://d29za44huniau5.cloudfront.net/uploads/2023/11/first-class-mobile.png",
                            LastName = "Johnson",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6780),
                            Specialization = "Zumba"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Olivia is a certified Pilates instructor with a passion for helping individuals improve their core strength and flexibility.",
                            FirstName = "Olivia",
                            ImageUrl = "https://www.clubpilates.com/hubfs/Leah-Pfrommer-Club-Pilates-instructor-exclusive-interview-with-Athletech-News-1.jpg",
                            LastName = "Williams",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6781),
                            Specialization = "Pilates"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Wolff is a certified strength training coach. He specializes in weightlifting and conditioning, helping clients build muscle and endurance.",
                            FirstName = "Wolff",
                            ImageUrl = "https://jwfitnesssystems.com/wp-content/uploads/2023/02/CW1_7335-scaled.jpg",
                            LastName = "Jameson",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6783),
                            Specialization = "Strength Training"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Conor Anthony McGregor is an Irish professional mixed martial artist, professional boxer, businessman and actor.",
                            FirstName = "Conor",
                            ImageUrl = "https://a.espncdn.com/i/headshots/mma/players/full/3022677.png",
                            LastName = "McGregor",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6784),
                            Specialization = "ММА"
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Log_22180022", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the operation was performed");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Type of operation performed (e.g., INSERT, UPDATE, DELETE)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the table where the operation occurred");

                    b.HasKey("Id");

                    b.ToTable("log_22180022", "22180022", t =>
                        {
                            t.HasComment("Log table for tracking database changes");
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "MembershipTypeId");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("MembershipRegistrations", "22180022");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the plan benefits");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration in days");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the membership plan");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the membership plan");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the membership");

                    b.HasKey("Id");

                    b.ToTable("MembershipTypes", "22180022");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A basic membership that grants access to all regular classes and gym facilities.",
                            Duration = 30,
                            ImageUrl = "https://i0.wp.com/poolstats.co/wp-content/uploads/2019/01/Basic-Membership.png?fit=400%2C327&ssl=1",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6818),
                            Name = "Basic",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "An elite membership offering access to all classes, gym facilities, and spa treatments.",
                            Duration = 60,
                            ImageUrl = "https://cdn.vectorstock.com/i/500p/49/16/elite-gold-label-vector-2944916.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Elite",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A premium membership offering access to all classes, gym facilities, and spa treatments.",
                            Duration = 180,
                            ImageUrl = "https://thumbs.dreamstime.com/b/premium-membership-badge-stamp-golden-red-ribbon-text-30827692.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6822),
                            Name = "Premium",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "An exclusive membership with additional perks including priority booking for events and personal training.",
                            Duration = 365,
                            ImageUrl = "https://cdn11.bigcommerce.com/s-2ooutu2zpl/images/stencil/original/products/35315/51564/VIP_Badge_2__62906.1641934958.png?c=2",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6824),
                            Name = "VIP",
                            Price = 499.99m
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Appointment date and time for the spa service");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Maximum capacity for the procedure");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the spa procedure");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the spa procedure in minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the spa procedure");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Spa type");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the spa procedure");

                    b.HasKey("Id");

                    b.ToTable("SpaProcedures", "22180022");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDateTime = new DateTime(2024, 12, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 5,
                            Description = "A soothing massage to relieve tension and stress.",
                            Duration = 60,
                            ImageUrl = "https://www.dshieldsusa.com/wp-content/uploads/2021/05/relaxing-massage-slide.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6861),
                            Name = "Relaxing Massage",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDateTime = new DateTime(2024, 12, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 1,
                            Description = "A rejuvenating facial to nourish and hydrate your skin.",
                            Duration = 45,
                            ImageUrl = "https://spamd.net/wp-content/uploads/2022/03/medications-facial-treatments.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6867),
                            Name = "Facial Treatment",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDateTime = new DateTime(2024, 12, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 2,
                            Description = "A session using essential oils to promote relaxation and well-being.",
                            Duration = 30,
                            ImageUrl = "https://elementsmassage.com/files/shared/AZ%20-%20Elements%20Massage%205-1864269.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6872),
                            Name = "Aromatherapy Session",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDateTime = new DateTime(2024, 12, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 3,
                            Description = "A therapeutic massage using smooth, heated stones to ease tension.",
                            Duration = 75,
                            ImageUrl = "https://images-prod.healthline.com/hlcmsresource/images/topic_centers/1296x728_HEADER_benefits-of-hot-stone-massage.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6878),
                            Name = "Hot Stone Massage",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDateTime = new DateTime(2024, 12, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 3,
                            Description = "A massage targeting deeper layers of muscle tissue to release chronic tension.",
                            Duration = 60,
                            ImageUrl = "https://propelphysiotherapy.com/wp-content/uploads/2023/08/what-is-deep-tissue-massage-therapy-propel-physiotherapy.jpg",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6882),
                            Name = "Deep Tissue Massage",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDateTime = new DateTime(2024, 12, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 3,
                            Description = "A detoxifying wrap using nutrient-rich seaweed to revitalize your skin.",
                            Duration = 90,
                            ImageUrl = "https://s3.amazonaws.com/salonclouds-uploads/blog/blog_1605466361125864114.png",
                            ModifiedOn_22180022 = new DateTime(2026, 4, 9, 13, 35, 24, 74, DateTimeKind.Utc).AddTicks(6887),
                            Name = "Seaweed Body Wrap",
                            Price = 85.00m
                        });
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaRegistration", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SpaProcedureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn_22180022")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of the last modification");

                    b.HasKey("MemberId", "SpaProcedureId");

                    b.HasIndex("SpaProcedureId");

                    b.ToTable("SpaRegistrations", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "22180022");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "22180022");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.Instructor", "Instructor")
                        .WithMany("FitnessClasses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClassRegistration", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.FitnessClass", "FitnessClass")
                        .WithMany("FitnessClassRegistrations")
                        .HasForeignKey("FitnessClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessClass");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEventRegistration", b =>
                {
                    b.HasOne("FitnessCenterApp.Data.Models.FitnessEvent", "FitnessEvent")
                        .WithMany("FitnessEventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessEvent");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipRegistration", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Data.Models.MembershipType", "MembershipType")
                        .WithMany("MembershipRegistrations")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaRegistration", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Data.Models.SpaProcedure", "SpaProcedure")
                        .WithMany("SpaRegistrations")
                        .HasForeignKey("SpaProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("SpaProcedure");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessClass", b =>
                {
                    b.Navigation("FitnessClassRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.FitnessEvent", b =>
                {
                    b.Navigation("FitnessEventRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.Instructor", b =>
                {
                    b.Navigation("FitnessClasses");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.MembershipType", b =>
                {
                    b.Navigation("MembershipRegistrations");
                });

            modelBuilder.Entity("FitnessCenterApp.Data.Models.SpaProcedure", b =>
                {
                    b.Navigation("SpaRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
